[2024-04-24T10:18:44.871+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T10:18:44.929+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality_exploration_dag_v1.transform_data_task scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-04-24T10:18:44.944+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality_exploration_dag_v1.transform_data_task scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-04-24T10:18:44.945+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-04-24T10:18:44.978+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-04-20 00:00:00+00:00
[2024-04-24T10:18:45.000+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-24T10:18:45.003+0000] {standard_task_runner.py:63} INFO - Started process 151 to run task
[2024-04-24T10:18:45.004+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_quality_exploration_dag_v1', 'transform_data_task', 'scheduled__2024-04-20T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/exploration_dag.py', '--cfg-path', '/tmp/tmpm4pxu496']
[2024-04-24T10:18:45.018+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask transform_data_task
[2024-04-24T10:18:45.113+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality_exploration_dag_v1.transform_data_task scheduled__2024-04-20T00:00:00+00:00 [running]> on host 13a839d238e9
[2024-04-24T10:18:45.511+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='data_quality_exploration_dag_v1' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-20T00:00:00+00:00'
[2024-04-24T10:18:45.515+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T10:18:45.545+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T10:18:45.547+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 43, in transform_data
    df["phone_number"] = df["phone_number"].apply(lambda x: "+62" + str(x))
                         ~~^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-04-24T10:18:45.568+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=data_quality_exploration_dag_v1, task_id=transform_data_task, execution_date=20240420T000000, start_date=20240424T101844, end_date=20240424T101845
[2024-04-24T10:18:45.596+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 105 for task transform_data_task (string indices must be integers, not 'str'; 151)
[2024-04-24T10:18:45.623+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-24T10:18:45.647+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T10:18:45.650+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
